package com.dbkj.meet.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("access_num", "id", AccessNum.class);
		arp.addMapping("account_balance", "id", AccountBalance.class);
		arp.addMapping("attendee", "id", Attendee.class);
		arp.addMapping("authority", "id", Authority.class);
		arp.addMapping("bill", "id", Bill.class);
		arp.addMapping("charge_record", "id", ChargeRecord.class);
		arp.addMapping("chargeback", "id", Chargeback.class);
		arp.addMapping("charging_mode", "id", ChargingMode.class);
		arp.addMapping("company", "id", Company.class);
		arp.addMapping("config", "id", Config.class);
		arp.addMapping("department", "id", Department.class);
		arp.addMapping("employee", "id", Employee.class);
		arp.addMapping("fee", "id", Fee.class);
		arp.addMapping("fixed_meet", "id", FixedMeet.class);
		arp.addMapping("group", "id", Group.class);
		arp.addMapping("order_attendee", "id", OrderAttendee.class);
		arp.addMapping("order_meet", "id", OrderMeet.class);
		arp.addMapping("package", "id", Package.class);
		arp.addMapping("private_contacts", "id", PrivateContacts.class);
		arp.addMapping("private_phone", "id", PrivatePhone.class);
		arp.addMapping("public_contacts", "id", PublicContacts.class);
		arp.addMapping("public_phone", "id", PublicPhone.class);
		arp.addMapping("record", "id", Record.class);
		arp.addMapping("schedule", "id", Schedule.class);
		arp.addMapping("sms", "id", Sms.class);
		arp.addMapping("smtp_email", "id", SmtpEmail.class);
		arp.addMapping("user", "id", User.class);
	}
}

