package com.dbkj.meet.model;

import com.dbkj.meet.model.base.BaseAccessNum;
import com.dbkj.meet.utils.SqlUtil;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AccessNum extends BaseAccessNum<AccessNum> {
	public static final AccessNum dao = new AccessNum();

	public List<AccessNum> list(){
		return find(SqlUtil.getSql("list",this));
	}
}
