package com.dbkj.meet.model;

import com.dbkj.meet.model.base.BaseAuthority;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Authority extends BaseAuthority<Authority> {
	public static final Authority dao = new Authority();
}
