package com.dbkj.meet.model;

import com.dbkj.meet.model.base.BaseChargebackRecord;
import com.jfinal.plugin.activerecord.Page;

import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChargebackRecord extends BaseChargebackRecord<ChargebackRecord> {
	public static final ChargebackRecord dao = new ChargebackRecord();

}
