package com.dbkj.meet.model;

import com.dbkj.meet.model.base.BaseCompany;
import com.dbkj.meet.utils.SqlUtil;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Company extends BaseCompany<Company> {
	public static final Company dao = new Company();

	/**
	 * 获取所有公司信息
	 * @return
     */
	public List<Company> getCompanys(){
		return find(SqlUtil.getSql("getCompanys",this));
	}

	/**
	 * 通过公司名称获取公司
	 * @param name
	 * @return
     */
	public Company getCompanyByName(String name){
		return findFirst(SqlUtil.getSql("getCompanyByName",this),name);
	}
}
