package com.dbkj.meet.model;

import com.dbkj.meet.model.base.BaseConfig;
import com.dbkj.meet.utils.SqlUtil;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Config extends BaseConfig<Config> {
	public static final Config dao = new Config();

	public Config findByType(int type){
		return findFirst(SqlUtil.getSql("findByType",this),type);
	}
}
