package com.dbkj.meet.model;

import com.dbkj.meet.model.base.BaseDepartment;
import com.dbkj.meet.utils.SqlUtil;
import com.jfinal.plugin.activerecord.Db;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Department extends BaseDepartment<Department> {
	public static final Department dao = new Department();

	public int deleteByCompanyId(long id){
		return Db.update(SqlUtil.getSql("deleteByCompanyId",this),id);
	}

	public List<Department> findByCompanyId(long id){
		return find(SqlUtil.getSql("findByCompanyId",this),id);
	}

	public Department findByName(String name,Long cid){
		return findFirst(SqlUtil.getSql("findByName",this),name,cid);
	}

}
