package com.dbkj.meet.model;

import com.dbkj.meet.model.base.BaseOrderMeet;
import com.dbkj.meet.model.common.DaoUtil;
import com.dbkj.meet.utils.SqlUtil;
import com.jfinal.plugin.activerecord.Db;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderMeet extends BaseOrderMeet<OrderMeet> {
	public static final OrderMeet dao = new OrderMeet();

	public int deleteByCompanyId(long id){
		return Db.update(SqlUtil.getSql("deleteByCompanyId",this),id);
	}

	public List<OrderMeet> getOrderMeetList(Map<String,Object> map){
		List<Object> params=new ArrayList<>();
		StringBuilder where=new StringBuilder(100);
		DaoUtil.getCondition(map,where,params);
		where.append(" ORDER BY created DESC");
		return find(SqlUtil.getSql("getOrderMeetList",this).concat(where.toString()),params.toArray());
	}
}
