package com.dbkj.meet.model;

import com.dbkj.meet.model.base.BaseOrderAttendee;
import com.dbkj.meet.model.common.DaoUtil;
import com.dbkj.meet.utils.SqlUtil;
import com.jfinal.plugin.activerecord.Db;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderAttendee extends BaseOrderAttendee<OrderAttendee> {
	public static final OrderAttendee dao = new OrderAttendee();

	public int deleteByCompanyId(long id){
		return Db.update(SqlUtil.getSql("deleteByCompanyId",this),id);
	}

	public List<OrderAttendee> findByOrderMeetId(long id){
		return find(SqlUtil.getSql("findByOrderMeetId",this),id);
	}

	public int deleteByOrderMeetId(long oid){
		return Db.update(SqlUtil.getSql("deleteByOrderMeetId",this),oid);
	}

	public List<OrderAttendee> getOrderAttendeeList(Map<String,Object> map){
		StringBuilder where=new StringBuilder(100);
		List<Object> params=new ArrayList<>();
		DaoUtil.getCondition(map,where,params);
		return find(SqlUtil.getSql("getOrderAttendeeList",this),params.toArray());
	}
}
