package com.dbkj.meet.model;

import com.dbkj.meet.model.base.BasePackage;
import com.dbkj.meet.utils.SqlUtil;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Package extends BasePackage<Package> {
	public static final Package dao = new Package();

	public final String CALLIN_RATE="callin_rate";
	public final String CALLIN_MODE="callin_mode";
	public final String PASS_RATE="pass_rate";
	public final String CALLOUT_RATE="callout_rate";
	public final String CALLOUT_MODE="callout_mode";
	public final String SMS_RATE="sms_rate";

	public List<Package> list(){
		return find(SqlUtil.getSql("list",this));
	}

	public Package findByName(String name){
		return findFirst(SqlUtil.getSql("findByName",this),name);
	}

	@Override
	public Package findById(Object id){
		return findFirst(SqlUtil.getSql("findById",this),id);
	}
}
