package com.dbkj.meet.model;

import com.dbkj.meet.model.base.BasePrivatePhone;
import com.dbkj.meet.utils.SqlUtil;
import com.jfinal.plugin.activerecord.Db;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PrivatePhone extends BasePrivatePhone<PrivatePhone> {
	public static final PrivatePhone dao = new PrivatePhone();

	public int deleteByCompanyId(long id){
		return Db.update(SqlUtil.getSql("deleteByCompanyId",this),id);
	}

	public int deleteByDepartmentId(long id){
		return Db.update(SqlUtil.getSql("deleteByDepartmentId",this),id);
	}

	public List<PrivatePhone> findNoGroupByUserId(long id){
		return find(SqlUtil.getSql("findNoGroupByUserId",this),id);
	}

	public int deleleByGroupId(long gid){
		return Db.update(SqlUtil.getSql("deleleByGroupId",this),gid);
	}

	public int deleteBatchById(int[] idArr){
		return deleteBatch(idArr,"deleteBatchById");
	}

	private int deleteBatch(int[] idArr,String str){
		if(idArr!=null){
			StringBuilder where=new StringBuilder(50);
			where.append("(");
			for(int i=0,len=idArr.length;i<len;i++){
				where.append(idArr[i]);
				if(i!=len-1){
					where.append(",");
				}

			}
			where.append(")");
			return Db.update(SqlUtil.getSql(str,this).concat(where.toString()));
		}
		return 0;
	}

	public int deleteBatchByContactId(int[] idArr){
		int count = deleteBatch(idArr,"deleteBatchByContactId");
		return count;
	}

	public List<PrivatePhone> findByContactId(long id){
		return find(SqlUtil.getSql("findByContactId",this),id);
	}
}
