package com.dbkj.meet.model;

import com.dbkj.meet.model.base.BasePublicPhone;
import com.dbkj.meet.utils.SqlUtil;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PublicPhone extends BasePublicPhone<PublicPhone> {
	public static final PublicPhone dao = new PublicPhone();

	public int deleteByCompanyId(long id){
		return Db.update(SqlUtil.getSql("deleteByCompanyId",this), id);
	}

	public int deleteByDepartmentId(long id){
		return Db.update(SqlUtil.getSql("deleteByDepartmentId",this),id);
	}

	public PublicPhone findByPhoneAndCompanyId(String phone,long cid){
		return findFirst(SqlUtil.getSql("findByPhoneAndCompanyId",this),cid,phone);
	}

	public int deleteBatch(int[] ids){
		if(ids!=null&&ids.length>0){
			StringBuilder sb=new StringBuilder(20);
			sb.append(" (");
			for(int i=0;i<ids.length;i++){
				sb.append(ids[i]);
				if(i!=ids.length-1){
					sb.append(",");
				}
			}
			sb.append(")");
			return Db.update(SqlUtil.getSql("deleteBatch",this)+sb.toString());
		}
		return 0;
	}
}
