package com.dbkj.meet.model;

import com.dbkj.meet.model.base.BaseSms;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sms extends BaseSms<Sms> {
	public static final Sms dao = new Sms();
}
