package com.dbkj.meet.model;

import com.dbkj.meet.model.base.BaseSmtpEmail;
import com.dbkj.meet.utils.SqlUtil;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmtpEmail extends BaseSmtpEmail<SmtpEmail> {
	public static final SmtpEmail dao = new SmtpEmail();

	public SmtpEmail findByUserId(long id){
		return findFirst(SqlUtil.getSql("findByUserId",this),id);
	}
}
