package com.dbkj.meet.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBill<M extends BaseBill<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setRid(java.lang.Long rid) {
		set("rid", rid);
	}

	public java.lang.Long getRid() {
		return get("rid");
	}

	public void setFee(java.math.BigDecimal fee) {
		set("fee", fee);
	}

	public java.math.BigDecimal getFee() {
		return get("fee");
	}

	public void setRate(java.lang.String rate) {
		set("rate", rate);
	}

	public java.lang.String getRate() {
		return get("rate");
	}

	public void setCaller(java.lang.String caller) {
		set("caller", caller);
	}

	public java.lang.String getCaller() {
		return get("caller");
	}

	public void setCallee(java.lang.String callee) {
		set("callee", callee);
	}

	public java.lang.String getCallee() {
		return get("callee");
	}

	public void setCallType(java.lang.Integer callType) {
		set("call_type", callType);
	}

	public java.lang.Integer getCallType() {
		return get("call_type");
	}

	public void setCallTime(java.lang.Integer callTime) {
		set("call_time", callTime);
	}

	public java.lang.Integer getCallTime() {
		return get("call_time");
	}

	public void setCallBeginTime(java.util.Date callBeginTime) {
		set("call_begin_time", callBeginTime);
	}

	public java.util.Date getCallBeginTime() {
		return get("call_begin_time");
	}

	public void setCallAnswerTime(java.util.Date callAnswerTime) {
		set("call_answer_time", callAnswerTime);
	}

	public java.util.Date getCallAnswerTime() {
		return get("call_answer_time");
	}

	public void setHangupTime(java.util.Date hangupTime) {
		set("hangup_time", hangupTime);
	}

	public java.util.Date getHangupTime() {
		return get("hangup_time");
	}

	public void setCallMode(java.lang.Integer callMode) {
		set("call_mode", callMode);
	}

	public java.lang.Integer getCallMode() {
		return get("call_mode");
	}

	public void setAnswer(java.lang.Integer answer) {
		set("answer", answer);
	}

	public java.lang.Integer getAnswer() {
		return get("answer");
	}

	public void setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
	}

	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	public void setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
	}

	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
