package com.dbkj.meet.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePackage<M extends BasePackage<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setCallin(java.lang.Long callin) {
		set("callin", callin);
	}

	public java.lang.Long getCallin() {
		return get("callin");
	}

	public void setCallout(java.lang.Long callout) {
		set("callout", callout);
	}

	public java.lang.Long getCallout() {
		return get("callout");
	}

	public void setSms(java.lang.Long sms) {
		set("sms", sms);
	}

	public java.lang.Long getSms() {
		return get("sms");
	}

	public void setDel(java.lang.Long del) {
		set("del", del);
	}

	public java.lang.Long getDel() {
		return get("del");
	}

	public void setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
	}

	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	public void setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
	}

	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

}
