package com.dbkj.meet.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setEid(java.lang.Integer eid) {
		set("eid", eid);
	}

	public java.lang.Integer getEid() {
		return get("eid");
	}

	public void setAid(java.lang.Integer aid) {
		set("aid", aid);
	}

	public java.lang.Integer getAid() {
		return get("aid");
	}

	public void setCid(java.lang.Integer cid) {
		set("cid", cid);
	}

	public java.lang.Integer getCid() {
		return get("cid");
	}

	public void setIsDel(java.lang.Integer isDel) {
		set("is_del", isDel);
	}

	public java.lang.Integer getIsDel() {
		return get("is_del");
	}

}
