package com.dbkj.meet.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSchedule<M extends BaseSchedule<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setOrderType(java.lang.Integer orderType) {
		set("orderType", orderType);
	}

	public java.lang.Integer getOrderType() {
		return get("orderType");
	}

	public void setInterval(java.lang.String interval) {
		set("interval", interval);
	}

	public java.lang.String getInterval() {
		return get("interval");
	}

	public void setOrderNum(java.lang.String orderNum) {
		set("orderNum", orderNum);
	}

	public java.lang.String getOrderNum() {
		return get("orderNum");
	}

	public void setOid(java.lang.Integer oid) {
		set("oid", oid);
	}

	public java.lang.Integer getOid() {
		return get("oid");
	}

	public void setJobName(java.lang.String jobName) {
		set("jobName", jobName);
	}

	public java.lang.String getJobName() {
		return get("jobName");
	}

	public void setJobGroup(java.lang.String jobGroup) {
		set("jobGroup", jobGroup);
	}

	public java.lang.String getJobGroup() {
		return get("jobGroup");
	}

}
