package com.dbkj.meet.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCompany<M extends BaseCompany<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setCallNum(java.lang.Integer callNum) {
		set("callNum", callNum);
	}

	public java.lang.Integer getCallNum() {
		return get("callNum");
	}

	public void setShowNum(java.lang.Integer showNum) {
		set("showNum", showNum);
	}

	public java.lang.Integer getShowNum() {
		return get("showNum");
	}

}
