package com.dbkj.meet.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRecord<M extends BaseRecord<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setSubject(java.lang.String subject) {
		set("subject", subject);
	}

	public java.lang.String getSubject() {
		return get("subject");
	}

	public void setHost(java.lang.String host) {
		set("host", host);
	}

	public java.lang.String getHost() {
		return get("host");
	}

	public void setStartTime(java.util.Date startTime) {
		set("startTime", startTime);
	}

	public java.util.Date getStartTime() {
		return get("startTime");
	}

	public void setEndTime(java.util.Date endTime) {
		set("endTime", endTime);
	}

	public java.util.Date getEndTime() {
		return get("endTime");
	}

	public void setIsRecord(java.lang.Integer isRecord) {
		set("isRecord", isRecord);
	}

	public java.lang.Integer getIsRecord() {
		return get("isRecord");
	}

	public void setBelong(java.lang.Integer belong) {
		set("belong", belong);
	}

	public java.lang.Integer getBelong() {
		return get("belong");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setHostPwd(java.lang.String hostPwd) {
		set("hostPwd", hostPwd);
	}

	public java.lang.String getHostPwd() {
		return get("hostPwd");
	}

	public void setListenerPwd(java.lang.String listenerPwd) {
		set("listenerPwd", listenerPwd);
	}

	public java.lang.String getListenerPwd() {
		return get("listenerPwd");
	}

	public void setMid(java.lang.String mid) {
		set("mid", mid);
	}

	public java.lang.String getMid() {
		return get("mid");
	}

	public void setHostName(java.lang.String hostName) {
		set("hostName", hostName);
	}

	public java.lang.String getHostName() {
		return get("hostName");
	}

	public void setMeetNums(java.lang.Integer meetNums) {
		set("meetNums", meetNums);
	}

	public java.lang.Integer getMeetNums() {
		return get("meetNums");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setSid(java.lang.Integer sid) {
		set("sid", sid);
	}

	public java.lang.Integer getSid() {
		return get("sid");
	}

	public void setRec(java.lang.String rec) {
		set("rec", rec);
	}

	public java.lang.String getRec() {
		return get("rec");
	}

	public void setCourtId(java.lang.String courtId) {
		set("courtId", courtId);
	}

	public java.lang.String getCourtId() {
		return get("courtId");
	}

	public void setCaseId(java.lang.String caseId) {
		set("caseId", caseId);
	}

	public java.lang.String getCaseId() {
		return get("caseId");
	}

	public void setNotice(java.lang.Integer notice) {
		set("notice", notice);
	}

	public java.lang.Integer getNotice() {
		return get("notice");
	}

	public void setAllowBegin(java.lang.Integer allowBegin) {
		set("allow_begin", allowBegin);
	}

	public java.lang.Integer getAllowBegin() {
		return get("allow_begin");
	}

}
