package com.dbkj.meet.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderMeet<M extends BaseOrderMeet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setSubject(java.lang.String subject) {
		set("subject", subject);
	}

	public java.lang.String getSubject() {
		return get("subject");
	}

	public void setStartTime(java.lang.String startTime) {
		set("startTime", startTime);
	}

	public java.lang.String getStartTime() {
		return get("startTime");
	}

	public void setHostName(java.lang.String hostName) {
		set("hostName", hostName);
	}

	public java.lang.String getHostName() {
		return get("hostName");
	}

	public void setHostNum(java.lang.String hostNum) {
		set("hostNum", hostNum);
	}

	public java.lang.String getHostNum() {
		return get("hostNum");
	}

	public void setHostPwd(java.lang.String hostPwd) {
		set("hostPwd", hostPwd);
	}

	public java.lang.String getHostPwd() {
		return get("hostPwd");
	}

	public void setIsRecord(java.lang.Integer isRecord) {
		set("isRecord", isRecord);
	}

	public java.lang.Integer getIsRecord() {
		return get("isRecord");
	}

	public void setBelong(java.lang.Integer belong) {
		set("belong", belong);
	}

	public java.lang.Integer getBelong() {
		return get("belong");
	}

	public void setSmsRemind(java.lang.Integer smsRemind) {
		set("sms_remind", smsRemind);
	}

	public java.lang.Integer getSmsRemind() {
		return get("sms_remind");
	}

	public void setIsCallInitiative(java.lang.Integer isCallInitiative) {
		set("is_call_initiative", isCallInitiative);
	}

	public java.lang.Integer getIsCallInitiative() {
		return get("is_call_initiative");
	}

	public void setRid(java.lang.Integer rid) {
		set("rid", rid);
	}

	public java.lang.Integer getRid() {
		return get("rid");
	}

	public void setGmtCreated(java.util.Date gmtCreated) {
		set("gmt_created", gmtCreated);
	}

	public java.util.Date getGmtCreated() {
		return get("gmt_created");
	}

	public void setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
	}

	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

}
