package com.dbkj.meet.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFixedMeet<M extends BaseFixedMeet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setSubject(java.lang.String subject) {
		set("subject", subject);
	}

	public java.lang.String getSubject() {
		return get("subject");
	}

	public void setHostName(java.lang.String hostName) {
		set("hostName", hostName);
	}

	public java.lang.String getHostName() {
		return get("hostName");
	}

	public void setHostPhone(java.lang.String hostPhone) {
		set("hostPhone", hostPhone);
	}

	public java.lang.String getHostPhone() {
		return get("hostPhone");
	}

	public void setHostPwd(java.lang.String hostPwd) {
		set("hostPwd", hostPwd);
	}

	public java.lang.String getHostPwd() {
		return get("hostPwd");
	}

	public void setListenerPwd(java.lang.String listenerPwd) {
		set("listenerPwd", listenerPwd);
	}

	public java.lang.String getListenerPwd() {
		return get("listenerPwd");
	}

	public void setBelong(java.lang.Integer belong) {
		set("belong", belong);
	}

	public java.lang.Integer getBelong() {
		return get("belong");
	}

	public void setCallNum(java.lang.String callNum) {
		set("callNum", callNum);
	}

	public java.lang.String getCallNum() {
		return get("callNum");
	}

	public void setMeetId(java.lang.String meetId) {
		set("meetId", meetId);
	}

	public java.lang.String getMeetId() {
		return get("meetId");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public void setShowNum(java.lang.String showNum) {
		set("showNum", showNum);
	}

	public java.lang.String getShowNum() {
		return get("showNum");
	}

	public void setIsRecord(java.lang.String isRecord) {
		set("isRecord", isRecord);
	}

	public java.lang.String getIsRecord() {
		return get("isRecord");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
